# Site settings
title: WJoan Blog
header-img: img/home-bg.jpg
email: wjoan822@qq.com
copyright_name: WJoan/WJoan.github.io/
description: "A blog about font-end technology"
baseurl: ""
url: "https://wjoan.github.io"
weibo_username: wjoan822
github_username: WJoan
email_username: wjoan822@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
