# Site settings
title: Joan's personal blog
description: A blog about front-end technology
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wang Jing
user_description: 1993年出生于北京，18岁来到武汉。本科、研究生均在华中科技大学计算机学院就读。热衷于前端开发。
email: joanwang822@qq.com
weibo_username: wjoan822
github_username:  WJoan
gplus_username:  none

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
